default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  timeout: 3000
  username: macbookpro
  password:

development:
  <<: *default
  database: cardcheck_development

test:
  <<: *default
  database: cardcheck_test

production:
  <<: *default
  database: cardcheck_production
